concurrency:
  cancel-in-progress: false
  group: "deploy"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: generate static files
        run: cargo run --release

      - name: commit README.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: update readme"
          file_pattern: "README.md"

      - uses: actions/upload-artifact@v3
        with:
          name: pages
          path: public/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: pages
          path: public/

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "public"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

name: deploy
on:
  push:
    branches: ["main"]

permissions:
  contents: write
  id-token: write
  pages: write
